### PR TITLE
Use stack; update cabal file and README (fixes #71 & #79)

### LINKED ISSUE #71: 7.8.4/32 installer: "string limit exceeded"
```
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386
Created uninstaller: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\uninstall.exe
Extract: ghc-7.8.4-i386.tar.xz
Extract: git-2.4.0.1.7z... 100%
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin
Extract: 7z.dll... 100%
Extract: 7z.exe... 100%
Extract: alex.7z
Extract: cabal.7z
Extract: happy.7z
Extract: minghc-post-install.exe.7z
Extract: stackage-cli.7z
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386
Execute: "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\7z.exe" x -y "-oC:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin" "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe.7z"
Delete file: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe.7z
Execute: "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe" "ghc-7.8.4-i386.tar.xz" "git-2.4.0.1.7z"
Delete file: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe
Create folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\switch
String limit exceeded
```

### PR DESCRIPTION
**Pull request by 3noch**
* Add stack.yaml
  * Update .gitignore for stack-specific things
  * Update GitHub links in cabal file
  * Update README
    * Describe need for large-string NSIS patch
    * Use stack in build instructions
    * No longer need lots of Unix tools on PATH

### CODE REVIEW

**Comment by 3noch** [comment]
I'll start uploading builds as soon as this hits `master`. Happy to change whatever you like.

**Comment by 3noch** [comment]
Oops, looks like I need to pull in a newer version of the nsis package than LTS provides.

**Comment by 3noch** [comment]
Fixed

**Comment by 3noch** [comment]
@snoyberg Thoughts?

**Comment by snoyberg** [comment]
Just got home, thus the delay. No thoughts, other than "looks good." Is there something possibly problematic here that I'm not seeing?

**Comment by 3noch** [comment]
Not that I can think of, but I wanted to make sure you were good with these changes.

**Comment by snoyberg** [comment]
That's how good I am with these changes ;)

**Comment by 3noch** [comment]
Now we're talking! ;)

**Pull request merged**
