### PR TITLE
Register uninstaller

### LINKED ISSUE #7: Register the uninstaller with Windows
From #6: minghc didn't register itself in Windows' "Add or remove programs", so I had to run uninstall.exe by hand.

Needs adding there, and removing from there on uninstall. Annoying, but not too hard.

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #7.

Questions/comments:

  * This registers the uninstaller for the current user only, for the simple reason that the install is user-local.
  * Do we have an icon we could add to both the installer and uninstaller?
  * Peruse the [other options](http://nsis.sourceforge.net/Add_uninstall_information_to_Add/Remove_Programs) to see if anything sticks out at you that we should add.

## Testing
I tested with default configuration.

### CODE REVIEW

**Comment by snoyberg** [comment]
I have no experience with uninstallers. @ndmitchell could I ask you to review this?

**Comment by ndmitchell** [comment]
Thoughts and comments:

* The typical uninstall icon setup is `uninstallIcon "$NSISDIR/contrib/graphics/icons/win-uninstall.ico"`. That's worth doing unless you have a better icon.
* `withReg` is just `flip uncurry`, so I'd probably inline it everywhere and just write `uncurry` - but entirely your choice.
* Would be easier to use `constantStr` than `constant` with a type signature - but you're copying the line before, so probably best to change either both or neither.

As for the actual uninstall stuff, that all looks thoroughly reasonable. Assuming you tested it once and it worked, that's enough for me. Thanks for the work!

The README improvements are also very good, well worth doing.

**Comment by 3noch** [comment]
@ndmitchell Great points. I'm on it.

**Comment by 3noch** [comment]
Looks like there's a bug in the uninstaller where it messes up the path pretty bad. It's preexisting though. I'll fix that while I'm at it.

**Comment by 3noch** [comment]
@ndmitchell Ready for another look. I did a bit of refactoring too.

**Comment by 3noch** [comment]
@ndmitchell Looks like the icon file is not available on Travis CI.

**Comment by 3noch** [comment]
Perhaps we can embed our own, from some free source: https://www.iconfinder.com/icons/62114/delete_garbage_remove_trash_icon#size=128

**Comment by ndmitchell** [comment]
Looks fine by me. I guess Linux doesn't include the icons. There are lots of free ones, so whichever you want. I think some of the MS ones are also licensed to allow use here, although not sure. What the uninstall icon looks like isn't too important :)

**Comment by 3noch** [comment]
@ndmitchell I haven't found any uninstall icons that look good. So here are our options:

  * Leave it as is, but builds only work on Windows and Travis CI is useless from now on [not recommended]
  * Copy the icon files from the Windows install and embed them
  * Someone look harder than I did for a good icon and embed it
  * Revert to not specifying icons at all

Pick your poison!

**Comment by 3noch** [comment]
Then again, the problem could be related to case-sensitive file systems....

**Comment by 3noch** [comment]
Looks like NSIS flattens casing anyway. How can I embed these icons? My attempts have failed so far.

**Comment by 3noch** [comment]
Or I forgot to change *both* paths. All green. Hope you enjoyed the annals of my struggling.

**Comment by Tralen** [comment]
Greetings,

I have made a few icons, hopefully the links work.

[Uninstall](https://iconverticons.com/icons/5b809afcb249ae64/)
[Regular](https://iconverticons.com/icons/3afc93d12d4dd205/)

For Windows, I believe you need the .ico.

**Comment by 3noch** [comment]
@Tralen Sweet! Very nice work. @ndmitchell How would I embed these? I couldn't quickly figure out how to refer to local files from within the overall setup section.

**Comment by ndmitchell** [comment]
@3noch I think the trick is to put them in the release directory, you have to distribute them. I have full details but won't have access until tonight, let me know if you need more.

**Comment by 3noch** [comment]
@ndmitchell I didn't see any place where we were distributing the built-in NSIS icons, so I would be surprised if we were forced to distribute this. The exes will embed them.

**Comment by ndmitchell** [comment]
I have just used `installIcon "./Icon.ico"`. Not sure if the `./` is required or not. You are right, I didn't seem to have to bundle them either.

**Comment by 3noch** [comment]
@ndmitchell Ok, I think it's finally ready.

**Comment by ndmitchell** [comment]
Fine by me. I'll leave @snoyberg to hit merge so the timing doesn't conflict with his other stuff.

**Comment by snoyberg** [comment]
I've got nothing in-flight right now, if you're good with it, we can merge now.

**Comment by ndmitchell** [comment]
Thanks for all your work on this @3noch

**Comment by 3noch** [comment]
My pleasure; just waiting on a release with builds.

**Comment by snoyberg** [comment]
Now that we have the Github-based releases, I think anyone should be able to generate the builds. @3noch you interested in becoming a maintainer of this project too and getting access for creating releases?

**Comment by ndmitchell** [comment]
+1!

**Comment by 3noch** [comment]
I'd be quite honored.

**Comment by snoyberg** [comment]
Invite sent, welcome to the team!

**Comment by 3noch** [comment]
I'm happy to be a part of this. Anything I need to know about the PGP signatures?

**Comment by ndmitchell** [comment]
Anything you need to know, I probably need to know too :) - I certainly don't know anything about them yet.

**Comment by Tralen** [comment]
If you ever need new icons, I will be pleased to help.

**Comment by 3noch** [comment]
@Tralen Thank you!

**Pull request merged**
