### PR TITLE
Point to 2015-06-23 release

### PR DESCRIPTION
**Pull request by 3noch**
Addresses #69.

Do some sanity checking if you're able.

### CODE REVIEW

**Comment by 3noch** [comment]
I'm currently testing these builds.

**Comment by 3noch** [comment]
I'm seeing a problem which I think I've encountered before. I wonder if newer cabal versions don't like building with older GHC versions. I'm using LTS-1.15 as the resolver in this build (but not with `stack`).

```
cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.22.2.0, now
Cabal-1.22.4.0). Additionally the compiler is different (was ghc-7.8, now ghc-7.10) which is probably the cause of the problem.
```

If I rerun the build it seems to work...

**Comment by 3noch** [comment]
Nevermind, I might not have properly cleared `cabal`'s intermediate files.

**Comment by 3noch** [comment]
I've tested both 64-bit versions with success.

**Comment by ndmitchell** [comment]
@3noch I get that error all the time - I just treat it as another sign that Cabal sucks.

**Comment by 3noch** [comment]
@ndmitchell It's quite possible. Cabal is an incredibly ambitious project with far too little help backing it up. It's a shame it has so many problems. But, it's laid the foundation for `stack`, which I think will quickly inaugurate a better story for Haskell.

**Comment by snoyberg** [comment]
You may be surprised to hear that this is expected behavior, not a bug.

https://github.com/haskell/cabal/issues/2611

At least, I know I was surprised. Anyway, it might get fixed this time.

**Comment by snoyberg** [comment]
I haven't been able to test this yet, but if others have feel free to merge it.

**Comment by 3noch** [comment]
I'd like at least one other person to confirm it works before I hit the big green button, since GitHub puts my name on this stuff and all... :wink:

**Comment by BethAr** [comment]
Well, I confirm the installation works, cabal on the other hand is giving me the `The version of Cabal being used has changed` error.

**Comment by snoyberg** [comment]
I just tested out the new 7.10.1 32-bit, and everything seems fine. :+1: looks good to release

**Comment by 3noch** [comment]
Thanks to both of you for testing. @snoyberg Let me know if there's a protocol for this and I'll just follow it. I'm unsure of myself at this point since I'm don't know how you guys have done it. Not to mention these releases affect a decently sized audience.

**Comment by snoyberg** [comment]
You're helping to define the protocol right now to be honest :) The ideal would be to get to the point where we have automated acceptance tests that are run on all the executables before release. However, I doubt we're going to get to that point. Spot checking seems reasonable for now.

**Comment by ndmitchell** [comment]
Yeah, our protocol, was guess, kick the tyres quickly, but mostly hope :)

**Pull request merged**
