### PR TITLE
Point to 2015-05-26 builds in README

### PR DESCRIPTION
**Pull request by 3noch**
Please:

  * Test for yourself
  * Advise regarding PGP signing
  * Advise regarding updating links on haskell.org

### CODE REVIEW

**Comment by 3noch** [comment]
After a release, do we want to delete the installers from old releases? I'm not sure how much space GitHub is willing to give us. The last I knew, GitHub was not fond of repos bigger than a couple GB. I'm guessing release builds fall into that same measurement. We we only keep the latest couple installers uploaded, we shouldn't have a problem.

**Comment by snoyberg** [comment]
* I'll try to test tomorrow
* PGP signing is a nice but optional step. If you're not set up to sign, don't worry about it
* We can send a PR to haskell.org after this PR is merged in, check out [my previous PR](https://github.com/haskell-infra/hl/pull/115/files) for guidance
* I don't know of any limits from Github on release sizes, and other projects seem to have very large releases (like PortableGit, which we're using). I don't want to delete the previous releases, it's useful. If Github doesn't like it, we can talk about it then

**Comment by snoyberg** [comment]
Installing now. I like the new icon :)

**Comment by snoyberg** [comment]
I've tested the 7.8.4 32-bit installer, and it looks good to me. I'm going to merge this. Are you OK with sending the PR to haskell.org yourself to get the links updated?

**Comment by snoyberg** [comment]
And thank you for doing this, good to have another member of the MinGHC team!

**Comment by 3noch** [comment]
Thanks for taking the time to test this out. It's a real pleasure being part of the team. [PR submitted](https://github.com/haskell-infra/hl/pull/117).

**Pull request merged**
