### PR TITLE
Add arch-specific alias for the switcher

### PR DESCRIPTION
**Pull request by 3noch**
I'm happy to oblige changes you'd like. I built with GHC 7.10.1 and it complained about `Main.hs`, hence the addition of `FlexibleContexts` extension. I'm not sure what the proper solution is.

This is the minimal work to address #27.

### CODE REVIEW

**Comment by 3noch** [comment]
@snoyberg @ndmitchell

**Comment by 3noch** [comment]
An improvement would be to decide on a "parent" script and then subsequently add *real* aliases for it, by simply calling it with a fully qualified path (so that the PATH doesn't interfere).

**Comment by ndmitchell** [comment]
Sorry, I was out all day today, but will take a look tomorrow. Thanks for the patch.

**Comment by ndmitchell** [comment]
Looks good, and FlexibleInstances is fine too.

Not sure what you mean by deciding on a parent script? The only advantage I can see is avoiding duplication between the .bat files - but I don't see that as a problem because although we've duplicated the files, our source only has them in once. Or were you referring to something else?

**Comment by 3noch** [comment]
@ndmitchell Sorry that was confusing. Yes, I meant avoiding the duplication in the resulting .bat files. We could choose a single bat file to contain the actual source and then the others would simply call that one. But I'm not worried about it if you aren't

**Comment by ndmitchell** [comment]
I think duplicating the batch files is probably safer, as it ensures if a user dislikes one alias they can just delete it. Finding batch files that are nearby is error prone anyway, since there's no easy way to call a path relative to your source.

**Pull request merged**
